### ISSUE TITLE
node4.3版本下，项目无法启动

### ISSUE THREAD

**Issue by wangshiyang3035884** [17koa/koa2-demo#1]
node4.3.0  npm 3.7.3 下unkoa下面的node_modules目录里没有es2015-node这个文件

**Comment by i5ting** [comment]
收到

**Comment by wssgcg1213** [comment]
@i5ting 我也发现这个问题 

``` bash
> MagicMessage@0.1.0 start /Users/Liuchenling/Sites/MagicMessage
> nodemon bin/run

[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node bin/run`
/Users/Liuchenling/Sites/MagicMessage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));
          ^

Error: Couldn't find preset "/Users/Liuchenling/Sites/MagicMessage/node_modules/runkoa/node_modules/babel-preset-es2015-node5" relative to directory "/Users/Liuchenling/Sites/MagicMessage/bin"
    at /Users/Liuchenling/Sites/MagicMessage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/Liuchenling/Sites/MagicMessage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/Liuchenling/Sites/MagicMessage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/Liuchenling/Sites/MagicMessage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.init (/Users/Liuchenling/Sites/MagicMessage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at compile (/Users/Liuchenling/Sites/MagicMessage/node_modules/babel-register/lib/node.js:81:45)
    at loader (/Users/Liuchenling/Sites/MagicMessage/node_modules/babel-register/lib/node.js:126:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Liuchenling/Sites/MagicMessage/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
[nodemon] app crashed - waiting for file changes before starting...
```

因为 npm3 扁平化了依赖,  所以直接查找
'node_modules/runkoa/node_modules/babel-preset-es2015-node5' 是会抛错的

**Comment by xinshouke** [comment]
I have met this issue on platform win10 and node v5.10.1, first, I new a issue to mgcrea... At last, I fix this issue as the above fix.
